/**
 * Writes src/data/tree/clustersGen.ts: the generated clusters of the passive tree (one per notable of the reference
 * that has an analog), from the reference (docs/tree/pob-tree.json), the names (docs/tree/names/*.json) and the
 * overrides (docs/tree/overrides.json). No reference name or line is written into src/.
 *
 *   npm run tree:emit
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { modsText } from '../../src/mods/text';
import type { ModT } from '../coverage/translate';
import { buildClusters, loadOverrides, SECTOR_REGION, TREE_DIR } from './clusters';
import { loadTreeRef } from './lines';
import { asMods, deniedNames, loadAllNames } from './names';
import { key } from '../coverage/reference';

export const OUT = resolve(TREE_DIR, '../../src/data/tree/clustersGen.ts');
const lit = (v: unknown): string => JSON.stringify(v);
const q = (s: string) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";

function modSource(m: ModT): string {
  const extra: string[] = [];
  if (m.damageTypes) extra.push(`damageTypes: ${lit(m.damageTypes)}`);
  if (m.tags) extra.push(`tags: ${lit(m.tags)}`);
  if (m.condition) extra.push(`condition: ${lit(m.condition)}`);
  if (m.per) extra.push(`per: ${lit(m.per)}`);
  const head = `m('${m.stat}', '${m.kind}', ${m.min}`;
  return extra.length ? `${head}, { ${extra.join(', ')} })` : `${head})`;
}

/** A name for a run of small nodes, from what they give: "Increased maximum Life" becomes "Maximum Life". */
export function smallName(mods: ModT[]): string {
  const text = modsText(asMods(mods.slice(0, 1)))[0] ?? 'Passive';
  const stripped = text
    .replace(/^[+\-−]?[\d.]+%?\s*/, '')
    .replace(/^(?:to |increased |reduced |more |less |of )+/i, '')
    .replace(/^additional /i, '')
    .trim();
  const s = stripped || text;
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const denied = deniedNames();
/** The name of the small nodes of a cluster, never a reference name (the phrase of some gems is also a stat phrase). */
const freeSmallName = (mods: ModT[]): string => {
  const n = smallName(mods);
  return denied.has(key(n)) ? `Lesser ${n.charAt(0).toLowerCase()}${n.slice(1)}` : n;
};

export async function render(): Promise<{ text: string; count: number; missing: number[] }> {
  const ref = loadTreeRef();
  const names = loadAllNames();
  const { built } = buildClusters(ref, loadOverrides());
  const missing = built.filter((b) => !names[String(b.ref)]).map((b) => b.ref);
  const rows = built
    .filter((b) => names[String(b.ref)])
    .map((b, i) => {
      const name = names[String(b.ref)];
      return `  {
    id: ${q('g' + i)},
    region: ${q(SECTOR_REGION[b.sector])},
    family: ${q(b.family)},
    depth: ${b.depth},
    smallCount: ${b.smallCount},
    notable: { name: ${q(name)}, mods: [${b.notable.map(modSource).join(', ')}] },
    small: { name: ${q(freeSmallName(b.small))}, mods: [${b.small.map(modSource).join(', ')}] },
  },`;
    });
  const raw = `import { mod as m } from '../../mods/types';
import type { GenCluster } from './types';

/**
 * The generated clusters of the passive tree: a notable and the small nodes beside it, each with mods in Bob's own
 * vocabulary. Generated by scripts/tree/emit.ts: edit docs/tree/names, docs/tree/overrides.json or the translator, not this
 * file. Every name is ours.
 */
export const GEN_CLUSTERS: GenCluster[] = [
${rows.join('\n')}
];
`;
  const text = await format(raw, { ...(await resolveConfig(OUT)), filepath: OUT });
  return { text, count: rows.length, missing };
}

async function main(): Promise<void> {
  const { text, count, missing } = await render();
  if (missing.length)
    console.log(`${missing.length} notables have no name yet; they are left out.`);
  writeFileSync(OUT, text);
  console.log(`emitted ${count} clusters to ${OUT}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) void main();
