import { hexTotals } from '../data/hexes';
import type { Minion } from './minions';
import { NO_SUP } from './minionSup';
import type { Actor } from './types';
import { newMoveState } from './movement';

/**
 * A fresh actor with every field at its neutral value; callers fill in what makes it a player, monster or minion.
 *
 * Every actor, whatever it is, is made with the same fields in the same order (the monster's `mon` and the minion's own
 * fields included, unset). The sim's hot loops read actors of all three kinds; one shape for all keeps those reads
 * monomorphic, where three shapes (and more as fields were added later) made them polymorphic and deoptimised them again
 * in every new map.
 */
export function newActor(id: number, isPlayer: boolean, x: number, y: number, r: number): Actor {
  const a: Minion = {
    id,
    isPlayer,
    faction: isPlayer ? 0 : 1,
    x,
    y,
    r,
    facing: 0,
    alive: true,
    life: 1,
    es: 0,
    mana: 0,
    def: undefined as never,
    action: null,
    carry: 0,
    handIdx: 0,
    ail: {
      ignites: [],
      igniteMax: 1,
      spreadEle: 0,
      bleeds: [],
      poisons: [],
      shock: 0,
      shockT: 0,
      chill: 0,
      chillT: 0,
      freezeT: 0,
    },
    stunT: 0,
    graceT: 0,
    leechLife: [],
    leechEs: [],
    leechMana: [],
    sinceDamaged: 99,
    tKill: 99,
    tCrit: 99,
    tHit: 99,
    tFlask: 99,
    tStunEnemy: 99,
    tBlock: 99,
    tBeenHit: 99,
    tOverload: 99,
    resShift: [0, 0, 0, 0, 0],
    resShiftT: 0,
    moving: false,
    name: '',
    rarity: 'player',
    modIds: [],
    room: -1,
    pack: -1,
    homeX: x,
    homeY: y,
    state: 'idle',
    lostT: 0,
    noticeT: 0,
    noReward: false,
    raiserT: 8,
    slamT: 7,
    bossPhase: 0,
    summonedBy: 0,
    dummy: false,
    retreatT: 0,
    retreatCd: 0,
    risen: false,
    skillT: 5,
    blinkT: 0,
    shellBy: 0,
    phaseT: 0,
    hexes: [],
    fx: {},
    impales: [],
    sdots: [],
    hexRes: [0, 0, 0, 0, 0],
    hexVulnAll: 0,
    hexVuln: 0,
    hexDmg: 1,
    hexSpeed: 1,
    hexMore: hexTotals([]),
    buffT: 0,
    zealT: 0,
    fervour: 0,
    fervourT: 0,
    hexCd: 0,
    channelT: 0,
    blockT: 0,
    prevX: x,
    prevY: y,
    tryTick: -1,
    beat: 0,
    patMult: 1,
    enraged: false,
    phaseMask: 0,
    mirrorId: 0,
    mirrorT: 0,
    strandT: 0,
    pulseT: 8,
    phases: false,
    mv: newMoveState(),
    revealT: 0,
    burrowT: 0,
    flies: false,
    stationary: false,
    curlT: 0,
    hold: false,
    patrol: null,
    patrolI: 1,
    pathT: 0,
    nextX: 0,
    nextY: 0,
    abT: [],
    dashT: 0,
    windT: 0,
    dashV: 0,
    fleeT: 0,
    stolen: 0,
    stolenFlask: 0,
    suppressT: 0,
    dashX: 0,
    dashY: 0,
    markX: 0,
    markY: 0,
    mon: undefined,
    key: '',
    kind: undefined as never,
    t: 0,
    atkT: 0,
    level: 0,
    dmg: 0,
    speed: 0,
    boomed: false,
    mtype: undefined,
    fixedHit: undefined,
    fixedRate: undefined,
    sup: NO_SUP,
    golem: undefined,
    bodyDef: undefined,
    defKey: undefined,
  };
  return a;
}
