import type { ActiveGemDef, SupportGemDef } from './gems';

/**
 * Gems of the coverage plan (C3 onward). Generated by scripts/coverage/emit-gems.ts from the decisions in
 * docs/coverage/gems/*.json: edit those, not this file. Every name and description is ours.
 */
export const GEN_ACTIVE_GEMS: ActiveGemDef[] = [];

export const GEN_SUPPORT_GEMS: SupportGemDef[] = [
  {
    kind: 'support',
    id: 'venomSeed',
    name: 'Venom Seed',
    attr: 'int',
    supports: [],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage.min',
        kind: 'base',
        value: [2, 137],
        damageTypes: ['chaos'],
      },
      {
        stat: 'damage.max',
        kind: 'base',
        value: [4, 205],
        damageTypes: ['chaos'],
      },
    ],
    description: 'Adds chaos damage to the hits of the supported skill.',
  },
  {
    kind: 'support',
    id: 'rimeSeed',
    name: 'Rime Seed',
    attr: 'dex',
    supports: [],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage.min',
        kind: 'base',
        value: [2, 150],
        damageTypes: ['cold'],
      },
      {
        stat: 'damage.max',
        kind: 'base',
        value: [4, 225],
        damageTypes: ['cold'],
      },
    ],
    description: 'Adds cold damage to the hits of the supported skill.',
  },
  {
    kind: 'support',
    id: 'sparkSeed',
    name: 'Spark Seed',
    attr: 'int',
    supports: [],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage.min',
        kind: 'base',
        value: [1, 20],
        damageTypes: ['lightning'],
      },
      {
        stat: 'damage.max',
        kind: 'base',
        value: [8, 400],
        damageTypes: ['lightning'],
      },
    ],
    description: 'Adds a wide spread of lightning damage to the hits of the supported skill.',
  },
  {
    kind: 'support',
    id: 'keenEye',
    name: 'Keen Eye',
    attr: 'dex',
    supports: ['attack'],
    costMult: 1.1,
    mods: [
      {
        stat: 'accuracy',
        kind: 'base',
        value: [20, 300],
      },
    ],
    description: 'Adds accuracy rating to the supported attack.',
  },
  {
    kind: 'support',
    id: 'rendingThirst',
    name: 'Rending Thirst',
    attr: 'str',
    supports: ['melee'],
    costMult: 1.25,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [40, 59],
        damageTypes: ['physical'],
        tags: ['melee'],
        condition: {
          id: 'targetBleeding',
        },
      },
      {
        stat: 'chance.bleed',
        kind: 'base',
        value: -1000,
      },
    ],
    description:
      'More melee physical damage against bleeding enemies, but the skill cannot cause bleeding.',
  },
  {
    kind: 'support',
    id: 'deepChill',
    name: 'Deep Chill',
    attr: 'int',
    supports: ['cold'],
    costMult: 1.2,
    mods: [
      {
        stat: 'effect.chill',
        kind: 'inc',
        value: [25, 44],
      },
    ],
    description: 'Increases the effect of the chill of cold skills.',
  },
  {
    kind: 'support',
    id: 'bluntIntent',
    name: 'Blunt Intent',
    attr: 'str',
    supports: [],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [40, 59],
        damageTypes: ['physical'],
      },
      {
        stat: 'noElementalDamage',
        kind: 'flag',
        value: 1,
      },
      {
        stat: 'noChaosDamage',
        kind: 'flag',
        value: 1,
      },
    ],
    description: 'More physical damage, but the skill deals no elemental or chaos damage.',
  },
  {
    kind: 'support',
    id: 'fannedFlame',
    name: 'Fanned Flame',
    attr: 'str',
    supports: [],
    costMult: 1.2,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [35, 54],
        tags: ['ignite'],
      },
    ],
    description: 'More damage from ignites.',
  },
  {
    kind: 'support',
    id: 'ricochet',
    name: 'Ricochet',
    attr: 'dex',
    supports: ['projectile', 'chaining'],
    excludes: ['channelling'],
    costMult: 1.5,
    mods: [
      {
        stat: 'chains',
        kind: 'base',
        value: 2,
      },
      {
        stat: 'damage',
        kind: 'more',
        value: [-30, -11],
      },
    ],
    description: 'Projectiles chain two additional times, at reduced damage.',
  },
  {
    kind: 'support',
    id: 'frostbreaker',
    name: 'Frostbreaker',
    attr: 'dex',
    supports: [],
    costMult: 1.4,
    mods: [
      {
        stat: 'penetration',
        kind: 'base',
        value: [18, 37],
        damageTypes: ['cold'],
      },
    ],
    description: 'Hits penetrate enemy cold resistance.',
  },
  {
    kind: 'support',
    id: 'tinderbox',
    name: 'Tinderbox',
    attr: 'int',
    supports: [],
    costMult: 1.2,
    mods: [
      {
        stat: 'chance.ignite',
        kind: 'base',
        value: [30, 49],
      },
      {
        stat: 'damage',
        kind: 'more',
        value: [10, 29],
        damageTypes: ['fire'],
      },
    ],
    description: 'A chance to ignite and more fire damage.',
  },
  {
    kind: 'support',
    id: 'mercyStroke',
    name: 'Mercy Stroke',
    attr: 'dex',
    supports: [],
    costMult: 1.1,
    mods: [
      {
        stat: 'cullingStrike',
        kind: 'flag',
        value: 1,
      },
      {
        stat: 'damage',
        kind: 'inc',
        value: [0, 38],
      },
    ],
    description:
      'Hits kill enemies left at 10% life or less, with a little more damage at higher levels.',
  },
  {
    kind: 'support',
    id: 'freshVigour',
    name: 'Fresh Vigour',
    attr: 'str',
    supports: ['attack'],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [30, 49],
        condition: {
          id: 'onFullLife',
        },
      },
    ],
    description: 'More damage while you are on full life.',
  },
  {
    kind: 'support',
    id: 'knifeRange',
    name: 'Knife Range',
    attr: 'dex',
    supports: ['melee'],
    costMult: 1.4,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [40, 59],
        tags: ['melee'],
        condition: {
          id: 'targetNearby',
        },
      },
    ],
    description: 'More melee damage against nearby enemies.',
  },
  {
    kind: 'support',
    id: 'lingeringCruelty',
    name: 'Lingering Cruelty',
    attr: 'dex',
    supports: [],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [45, 64],
        tags: ['dot'],
      },
      {
        stat: 'damage',
        kind: 'more',
        value: -10,
        tags: ['hit'],
      },
    ],
    description: 'More damage over time from ailments, but less damage from hits.',
  },
  {
    kind: 'support',
    id: 'slowRot',
    name: 'Slow Rot',
    attr: 'int',
    supports: [],
    costMult: 1.3,
    mods: [
      {
        stat: 'chance.poison',
        kind: 'base',
        value: 100,
      },
      {
        stat: 'duration.poison',
        kind: 'inc',
        value: 400,
      },
    ],
    description: 'Hits always poison, and the poison lasts much longer.',
  },
  {
    kind: 'support',
    id: 'patientPower',
    name: 'Patient Power',
    attr: 'int',
    supports: [],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [10, 20],
        tags: ['spell'],
      },
      {
        stat: 'damage',
        kind: 'more',
        value: [15, 24],
        tags: ['dot'],
      },
    ],
    description: 'More damage from spells and from damage over time.',
  },
  {
    kind: 'support',
    id: 'elementalEdge',
    name: 'Elemental Edge',
    attr: 'str',
    supports: ['attack'],
    costMult: 1.4,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [35, 54],
        damageTypes: ['fire', 'cold', 'lightning'],
      },
    ],
    description: 'More elemental damage with attacks.',
  },
  {
    kind: 'support',
    id: 'swiftFlight',
    name: 'Swift Flight',
    attr: 'dex',
    supports: ['projectile'],
    costMult: 1.1,
    mods: [
      {
        stat: 'projectileSpeed',
        kind: 'inc',
        value: [50, 69],
      },
      {
        stat: 'damage',
        kind: 'inc',
        value: [20, 29],
        tags: ['projectile'],
      },
    ],
    description: 'Increased projectile speed and projectile damage.',
  },
  {
    kind: 'support',
    id: 'ashbreaker',
    name: 'Ashbreaker',
    attr: 'str',
    supports: [],
    costMult: 1.4,
    mods: [
      {
        stat: 'penetration',
        kind: 'base',
        value: [18, 37],
        damageTypes: ['fire'],
      },
    ],
    description: 'Hits penetrate enemy fire resistance.',
  },
  {
    kind: 'support',
    id: 'bulwarkStrikes',
    name: 'Bulwark Strikes',
    attr: 'str',
    supports: ['melee'],
    costMult: 1.3,
    mods: [
      {
        stat: 'damage',
        kind: 'more',
        value: [20, 34],
        tags: ['melee'],
      },
      {
        stat: 'buffOn.meleeHit.fortify',
        kind: 'base',
        value: 100,
      },
    ],
    description: 'More melee damage, and melee hits make you Fortified.',
  },
  {
    kind: 'support',
    id: 'tideGathering',
    name: 'Tide Gathering',
    attr: 'int',
    supports: ['spell'],
    excludes: ['totem', 'trap', 'mine', 'triggered'],
    costMult: 1.3,
    mods: [
      {
        stat: 'buffOn.cast.arcaneSurge',
        kind: 'base',
        value: 100,
      },
    ],
    description: 'Casting the supported spell grants Arcane Tide.',
  },
  {
    kind: 'support',
    id: 'staggerResolve',
    name: 'Stagger Resolve',
    attr: 'str',
    supports: ['melee'],
    costMult: 1.1,
    mods: [
      {
        stat: 'enemyStunThreshold',
        kind: 'base',
        value: [0, 19],
      },
      {
        stat: 'chargeOn.stun.grit',
        kind: 'base',
        value: 100,
      },
    ],
    description: 'Melee stuns are easier and grant a Grit charge.',
  },
  {
    kind: 'support',
    id: 'exaltedFocus',
    name: 'Exalted Focus',
    attr: 'str',
    supports: [],
    costMult: 1.25,
    levelBonus: [0, 9],
    mods: [],
    description: 'Raises the level of the supported skill.',
  },
];
